language: node_js
node_js:
  - 14.16.0

cache:
  directories:
  - node_modules

script:
  - npm run configClient
  - npm run buildClient

deploy:
  - provider: heroku
    strategy: git
    app: 
      main: t093iu-web-app-server
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: client/build
    on:
      branch: main
